export type MigrantWorker = {
  id: number;
  name: string;
  "Full Name": string;
  age: number;
  "Age": number;
  phone: string;
  "Phone Number": string;
  email?: string;
  "Email Address"?: string;
  "Primary Skill": string;
  "Origin State": string;
  status: "active" | "inactive" | "pending";
  registrationDate: string;
  "Photo URL"?: string;
  photoUrl?: string;
  latitude?: number;
  longitude?: number;
  aadhaar: string;
  "Aadhaar Number": string;
  assignedBusinessId?: string;
};
